loom.platform=neoforge
java.version=25
deps.minecraft=26.3
neoforge.version=26.3.0.1-beta
cloth.version=26.3.158
glsl.transformer.version=3.0.0-pre3
deps.minecraftRange=[26.3]
deps.loaderRange=[26.3.0.1-beta,)
deps.clothRange=[26.3.158,27)
sodium.version=mc26.3-0.9.2-neoforge
iris.compile.version=1.11.6+26.3-fabric
era.sources=mc26,mc26.3
