java.version=17
deps.minecraft=1.20.1
loader.version=0.19.3
fabric.version=0.92.12+1.20.1
cloth.version=11.1.136
modmenu.version=7.2.2
glsl.transformer.version=2.0.1
deps.clothRange=>=11.1.136 <12
deps.modmenuRange=>=7.2.2 <8
sodium.version=mc1.20.1-0.5.13-fabric
iris.version=1.7.6+1.20.1
era.sources=gl,mc1.20.1
