java.version=25
deps.minecraft=26.2
loader.version=0.19.5
fabric.version=0.160.0+26.2
cloth.version=26.2.155
modmenu.version=20.0.2
glsl.transformer.version=3.0.0-pre3
deps.clothRange=>=26.2.155 <27
deps.modmenuRange=>=20.0.2 <21
sodium.version=mc26.2-0.9.2-fabric
iris.version=1.11.4+26.2-fabric
era.sources=mc26,mc26.2
