loom.platform=neoforge
java.version=25
deps.minecraft=26.2
neoforge.version=26.2.0.88
cloth.version=26.2.155
glsl.transformer.version=3.0.0-pre3
deps.minecraftRange=[26.2]
deps.loaderRange=[26.2.0.88,)
deps.clothRange=[26.2.155,27)
sodium.version=mc26.2-0.9.2-neoforge
iris.version=1.11.4+26.2-neoforge
era.sources=mc26,mc26.2
