java.version=21
deps.minecraft=1.21.1
loader.version=0.19.3
fabric.version=0.116.14+1.21.1
cloth.version=15.0.140
modmenu.version=11.0.3
sodium.version=mc1.21.1-0.6.13-fabric
iris.version=1.8.8+1.21.1-fabric
embeddium.version=1.0.15+mc1.21.1
glsl.transformer.version=2.0.1
deps.clothRange=>=15.0.140 <16
deps.modmenuRange=>=11.0.3 <12
era.sources=gl,mc1.21.1
