loom.platform=forge
java.version=17
deps.minecraft=1.20.1
forge.version=1.20.1-47.4.23
cloth.version=11.1.136
glsl.transformer.version=2.0.1
deps.minecraftRange=[1.20.1]
deps.loaderRange=[47.4,)
deps.clothRange=[11.1.136,12)
era.sources=gl,mc1.20.1
iris.slug=oculus
iris.version=1.20.1-1.8.0
mixinextras.version=0.5.5
embeddium.version=0.3.31+mc1.20.1
rubidium.version=0.7.1
